import type { SpeedPreset, SpeedMode } from '../stores/gameStore'
import type { TimelineBlock } from '../stores/timelineStore'

// ─── Shared Types ──────────────────────────────────────────────────────────────

export interface GameExportData {
    speedMode: SpeedMode
    preset: SpeedPreset
    winDuration: number       // ms
    currentLines: number
}

export interface TimelineExportData {
    blocks: TimelineBlock[]
    totalDuration: number
}

// ─── Helpers ───────────────────────────────────────────────────────────────────

function triggerDownload(content: string, filename: string, mimeType: string): void {
    const blob = new Blob([content], { type: mimeType })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
}

function getTimestamp(): string {
    // Format: YYYYMMDD_HHmmss
    const now = new Date()
    const pad = (n: number) => String(n).padStart(2, '0')
    return (
        `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}` +
        `_${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`
    )
}

// ─── Markdown Exporter ─────────────────────────────────────────────────────────

export function generateSpecMarkdown(gameData: GameExportData, _timelineData: TimelineExportData): void {
    const { preset, speedMode, winDuration, currentLines } = gameData
    const ts = getTimestamp()

    const md = [
        `# SlotForge 規格書`,
        ``,
        `> 匯出時間: ${new Date().toISOString()}`,
        ``,
        `## 基本設定`,
        ``,
        `| 參數 | 數值 |`,
        `|------|------|`,
        `| 速度模式 | \`${speedMode}\` |`,
        `| 線數 | ${currentLines} |`,
        ``,
        `## 四段物理參數（Physics Phases）`,
        ``,
        `| 階段 | 說明 | 時間 (ms) |`,
        `|------|------|-----------|`,
        `| P1 | Spin（高速滾動） | ${preset.spinDuration} |`,
        `| P2 | Decelerate（減速） | ${preset.decelerateDuration} |`,
        `| P3 | Align（對齊） | ${preset.alignDuration} |`,
        `| P4 | Settle（微彈） | ${preset.settleDuration} |`,
        ``,
        `## 捲軸間距（Interval）`,
        ``,
        `| 參數 | 數值 |`,
        `|------|------|`,
        `| P5 捲軸間距 | ${preset.intervalBetweenReels} ms |`,
        ``,
        `## Win Demo 設定`,
        ``,
        `| 階段 | 起始金額 | 持續時間 (ms) |`,
        `|------|----------|---------------|`,
        `| Small | 0 | 1,500 |`,
        `| Big | 1,000 | ${winDuration} |`,
        `| Mega | 5,000 | ${winDuration} |`,
        `| Super | 20,000 | ${winDuration} |`,
        `| Epic | 50,000 | ${winDuration} |`,
        ``,
        `---`,
        `*Generated by SlotForge v2.0*`,
    ].join('\n')

    triggerDownload(md, `SlotSpec_${ts}.md`, 'text/markdown')
}

// ─── Cocos Creator JSON Exporter ───────────────────────────────────────────────

export function generateCocosJSON(gameData: GameExportData, _timelineData: TimelineExportData): void {
    const { preset, speedMode, winDuration, currentLines } = gameData
    const ts = getTimestamp()

    const config = {
        version: '1.0.0',
        targetEngine: 'CocosCreator',
        exportedAt: new Date().toISOString(),
        speedMode,
        currentLines,
        physics: {
            phases: {
                P1_spin_ms: preset.spinDuration,
                P2_decelerate_ms: preset.decelerateDuration,
                P3_align_ms: preset.alignDuration,
                P4_settle_ms: preset.settleDuration,
            },
            interval: preset.intervalBetweenReels,
            // Additional physics params
            spinSymbolCount: preset.spinSymbolCount,
            decelerateSymbolCount: preset.decelerateSymbolCount,
            overshootSymbols: preset.overshootSymbols,
            bounceStrength: preset.bounceStrength,
        },
        winPresentation: {
            thresholds: {
                small: 0,
                big: 1000,
                mega: 5000,
                super: 20000,
                epic: 50000,
            },
            durations: {
                small_ms: 1500,
                base_ms: winDuration,
            },
        },
    }

    const jsonString = JSON.stringify(config, null, 2)
    triggerDownload(jsonString, `SlotConfig_${ts}.json`, 'application/json')
}
